#!/bin/bash

export J2OBJC_HOME=/Users/ernesto.torres/Documents/j2objc-2.0.5
export J2OBJC_NULLABILITY=${J2OBJC_HOME}/lib/jsr305-3.0.0.jar
export J2OBJC_SOURCES=../../../HNCore/Java-core/src/main/
export J2OBJC_DST=../HNCore/Autogenerated/

echo "Generating Obj-C files"
if [ ! -f "${J2OBJC_HOME}/j2objc" ]; then echo "J2OBJC_HOME is not correctly defined, currently set to '${J2OBJC_HOME}'"; exit 1; fi;
"${J2OBJC_HOME}/j2objc" -d "$J2OBJC_DST" -sourcepath "${J2OBJC_SOURCES}" --prefix io.ernesto.hn=IOE --no-package-directories -use-arc --swift-friendly -g -v -classpath "${J2OBJC_NULLABILITY}" `find "${J2OBJC_SOURCES}" -name '*.java'`;
