# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'hackyto' do
    pod 'Firebase', '>= 1.2.2'
    pod 'MBProgressHUD', '~> 0.9'
    pod 'PureLayout'
end

target 'HackytoTests' do

end

