//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../HNCore/Java-core/src/main//java/io/ernesto/hn/HackerNewsAPI.java
//

#include "ContentProvider.h"
#include "HackerNewsAPI.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nullable.h"

@interface IOEHackerNewsAPI () {
 @public
  NSString *baseURL_;
  NSString *topStoriesPath_;
  NSString *newStoriesPath_;
  NSString *askStoriesPath_;
  NSString *showStoriesPath_;
  NSString *jobStoriesPath_;
  IOEContentProvider *provider_;
}

@end

J2OBJC_FIELD_SETTER(IOEHackerNewsAPI, baseURL_, NSString *)
J2OBJC_FIELD_SETTER(IOEHackerNewsAPI, topStoriesPath_, NSString *)
J2OBJC_FIELD_SETTER(IOEHackerNewsAPI, newStoriesPath_, NSString *)
J2OBJC_FIELD_SETTER(IOEHackerNewsAPI, askStoriesPath_, NSString *)
J2OBJC_FIELD_SETTER(IOEHackerNewsAPI, showStoriesPath_, NSString *)
J2OBJC_FIELD_SETTER(IOEHackerNewsAPI, jobStoriesPath_, NSString *)
J2OBJC_FIELD_SETTER(IOEHackerNewsAPI, provider_, IOEContentProvider *)

__attribute__((unused)) static IOSObjectArray *IOEHackerNewsAPI__Annotations$0();

#line 1 "/Users/ernesto.torres/Documents/Repositories/Personal/HackerNews/HNCore/Java-core/src/main/java/io/ernesto/hn/HackerNewsAPI.java"


#line 14
@implementation IOEHackerNewsAPI

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 26
- (instancetype)init {
  IOEHackerNewsAPI_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 30
- (IOSObjectArray * __nullable)fetch {
  
#line 32
  return [((IOEContentProvider *) nil_chk(provider_)) getStories];
}


#line 35
- (void)next {
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[LIOEStory;", 0x1, -1, -1, -1, -1, 0, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(fetch);
  methods[2].selector = @selector(next);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "baseURL_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "topStoriesPath_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "newStoriesPath_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "askStoriesPath_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "showStoriesPath_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "jobStoriesPath_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "provider_", "LIOEContentProvider;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { (void *)&IOEHackerNewsAPI__Annotations$0 };
  static const J2ObjcClassInfo _IOEHackerNewsAPI = { "HackerNewsAPI", "io.ernesto.hn", ptrTable, methods, fields, 7, 0x1, 3, 7, -1, -1, -1, -1, -1 };
  return &_IOEHackerNewsAPI;
}

@end


#line 26
void IOEHackerNewsAPI_init(IOEHackerNewsAPI *self) {
  NSObject_init(self);
  self->baseURL_ =
#line 15
  @"https://hacker-news.firebaseio.com/v0/";
  self->topStoriesPath_ =
#line 17
  @"topstories.json";
  self->newStoriesPath_ = @"newstories.json";
  self->askStoriesPath_ = @"askstories.json";
  self->showStoriesPath_ = @"showstories.json";
  self->jobStoriesPath_ = @"jobstories.json";
  
#line 27
  self->provider_ = new_IOEContentProvider_initWithNSString_withNSString_(self->baseURL_, self->topStoriesPath_);
}


#line 26
IOEHackerNewsAPI *new_IOEHackerNewsAPI_init() {
  J2OBJC_NEW_IMPL(IOEHackerNewsAPI, init)
}


#line 26
IOEHackerNewsAPI *create_IOEHackerNewsAPI_init() {
  J2OBJC_CREATE_IMPL(IOEHackerNewsAPI, init)
}

IOSObjectArray *IOEHackerNewsAPI__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNullable() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IOEHackerNewsAPI)
