//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../../../HNCore/Java-core/src/main//java/io/ernesto/hn/Story.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Story")
#ifdef RESTRICT_Story
#define INCLUDE_ALL_Story 0
#else
#define INCLUDE_ALL_Story 1
#endif
#undef RESTRICT_Story

#if !defined (IOEStory_) && (INCLUDE_ALL_Story || defined(INCLUDE_IOEStory))
#define IOEStory_

@interface IOEStory : NSObject

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)title
                    withNSString:(NSString *)author
                    withNSString:(NSString *)comments
                    withNSString:(NSString *)url;

- (NSString *)getTitle;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(IOEStory)

FOUNDATION_EXPORT void IOEStory_initWithNSString_withNSString_withNSString_withNSString_(IOEStory *self, NSString *title, NSString *author, NSString *comments, NSString *url);

FOUNDATION_EXPORT IOEStory *new_IOEStory_initWithNSString_withNSString_withNSString_withNSString_(NSString *title, NSString *author, NSString *comments, NSString *url) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IOEStory *create_IOEStory_initWithNSString_withNSString_withNSString_withNSString_(NSString *title, NSString *author, NSString *comments, NSString *url);

J2OBJC_TYPE_LITERAL_HEADER(IOEStory)

@compatibility_alias IoErnestoHnStory IOEStory;

#endif

#pragma pop_macro("INCLUDE_ALL_Story")
